### ISSUE TITLE
同为micro 框架使用者希望能共同交流

### ISSUE THREAD

**Issue by anbsyipeu** [xbox1994/go-micro-example#1]
你好，我最近对micro 关注了不少，而且也用micro 实现了几个服务 ，看了你的实现方式 我想说一下我的架构 我的架构如下
micro api （8080对外接口） 感觉/rpc 不应该暴露，作者想法是api服务本来就在代理服务器后面所以不妨，而且提供了一个插件关闭，总觉的不够清真
|---micro.api.rmanage   用户管理与认证中心api服务 （8080将数据直接转发给rmanange.api服务，由rmanange.api服务进行认证头token的剥离，并将认证头附在下一步请求中）
    |----micro.srv.rmanage   用户管理与认证中心srv服务 （由rmanange.api服务进行转发，在rmanage.srv中进行真正的认证相关的逻辑处理，返回结果继续返回给rmanange.api）
实现框架 
api.rmanage用了go-restful 对api网关提供restful接口
srv.rmanage数据库orm 用了gorm 
配置中心直接将数据存在了consul,使用了自带的go-config获取配置
部署用的docker，还没有到CD/CI这一步
限流熔断什么的打算直接用go-plugin中的插件

遇到的问题
1、作者自带的cors插件、header插件都不能用、看了源码给作者提了点意见，作者没时间让我pr，但是感觉不太敢动他的源码怕不够理解他的框架意图
2、api.rmanage你觉的是否有必要
3、srv 开发时 你有没有觉的比较好的规范，我自己设计了一套但是感觉还是不太如意
4、api网关 换用其他开源如eolinker/GoKu-API-Gateway 的必要性及可行性
5、与rpcx 这个框架的对比（rpcx官网的性能对比将micro的性能贬的一文不值，但我觉的他的文章有失公正，或是在自说自话）

给作者提过几个issus但是毕竟语言不方便，而且资料确实太少，目前知道的只有华尔街日报用了这个框架，但是没有落地的技术资料，希望能跟你更多的交流

**Comment by xbox1994** [comment]
你好，非常高兴能碰到志同道合的小伙伴，我也是刚开始接触这个框架，也碰到资料太少的问题，所以一些我的实现是按我自己和同事的想法来的，仅供参考。

我刚更新了我这个例子的readme，架构看起来清晰些了。跟你的一个区别在于我把作者的api与srv两个层级合并成为一个层级也就是一个服务，我始终觉得分成api与srv两层对于一个系统来说有点太细了，在开发部署测试方面都会大大增加难度，一个项目在一开始就分这么细有点过度设计了，以后根据情况再来。

另一个区别是我把用户验证服务放到了micro api里，是一个api网关的插件，在微服务的架构里，我觉得这是网关应该做的一个事情因为每个请求都会需要验证，micro api其实就是一个服务了，再单独做个服务就没太大必要了。

至于orm框架、配置中心、限流，怎样用着方便就怎样来吧，我是觉得micro框架里提供的很难用，就用的beego的orm，spring cloud config和hystrix，哈哈。

以上回答了你部分问题，其他问题我也不太清楚，我也是刚刚接触go语言个这个框架，我们做的项目也刚刚上线，看情况再做优化之后再来这里更新。
